name = "BinaryHypervectors"
uuid = "26f24e0d-335a-4f16-b355-0381354a1c80"
authors = ["Garrett Smith <gasmith@uni-potsdam.de> and contributors"]
version = "2023.0.0-07-26"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
